fix TypeError: db.collection is not a function
issue due to different version of mongodb used by tutorial video and latest version

solution found on https://stackoverflow.com/a/47694265