Fix my dumbass error of a typo that caused TypeError: authHeader.spilt is not a function at auth by moving it into the correct area so bodyParser can do its work and fixing typo errors